version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  product_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - product_db_data:/var/lib/postgresql/data

  order_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - order_db_data:/var/lib/postgresql/data

  customer_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - customer_db_data:/var/lib/postgresql/data

  product_service:
    build: ./backend/product_service
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: product_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - product_db
      - rabbitmq

  order_service:
    build: ./backend/order_service
    ports:
      - "8001:8000"
    environment:
      POSTGRES_HOST: order_db
      CUSTOMER_SERVICE_URL: http://customer_service:8000
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - order_db
      - rabbitmq
      - customer_service

  customer_service:
    build: ./backend/customer_service
    ports:
      - "8002:8000"
    environment:
      POSTGRES_HOST: customer_db
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - customer_db
      - rabbitmq

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - product_service
      - order_service
      - customer_service

volumes:
  product_db_data:
  order_db_data:
  customer_db_data:
