apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use base manifests
resources:
  - ../../base

# Patch images to point to your local ACR (from local.tfvars)
images:
  - name: product_service
    newName: sit722aklocalacr.azurecr.io/product_service
    newTag: latest
  - name: order_service
    newName: sit722aklocalacr.azurecr.io/order_service
    newTag: latest
  - name: customer_service
    newName: sit722aklocalacr.azurecr.io/customer_service
    newTag: latest
  - name: frontend
    newName: sit722aklocalacr.azurecr.io/frontend
    newTag: latest
