apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-db-pvc
  labels:
    app: product-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
  labels:
    app: product-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: global-config
                  key: PRODUCT_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: product-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: product-db-storage
          persistentVolumeClaim:
            claimName: product-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: product-db
  labels:
    app: product-db
spec:
  selector:
    app: product-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
